version: "3.3"

networks:
  solidinvoice:

services:
  db:
    image: "mysql:8.0"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - solidinvoice

  app:
    build:
      context: ./docker/
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ".:/opt/srv"
    environment:
      SOLIDINVOICE_ENV: dev
      SOLIDINVOICE_DEBUG: 1
      database_driver: pdo_mysql
      database_host: db
      database_port: 3306
      database_name: solidinvoice
      database_user: root
      database_password:
    networks:
      - solidinvoice

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_HOST:db
      - PMA_PORT:3300
      - PMA_USER:root
    networks:
      - solidinvoice

volumes:
  db_data: {}
